import './globals.css'
import { Inter } from 'next/font/google'
import Header from './header/page'
import Sidebar from './sidebar/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div><Header /></div>
        <div style={{display:"flex"}}>
          <div>
            <Sidebar />
          </div>
          <div>{children}</div>
        </div>
      </body>
    </html>
  )
}
